global:
  scrape_interval: 15s

scrape_configs:
  # - job_name: "prometheus"

  #   static_configs:
  #     - targets: ["localhost:9090"]

  # - job_name: "tns_app"

  #   # Override global settings
  #   scrape_interval: 5s

  #   static_configs:
  #     - targets: ["app:80"]

  - job_name: 'site_probes'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Use default HTTP probe module
    static_configs:
      - targets:
        - https://voltrack.transvolt.org
        - https://issuetracker.transvolt.org
        - https://czapi.transvolt.org        
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # Tell Prometheus to send probes to Blackbox Exporter

